package by.pvt.dao;

import by.pvt.dto.ClientFeedback;
import by.pvt.dto.ClientFeedbackExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClientFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_feedback
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    long countByExample(ClientFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_feedback
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    int deleteByExample(ClientFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_feedback
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    int insert(ClientFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_feedback
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    int insertSelective(ClientFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_feedback
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    List<ClientFeedback> selectByExample(ClientFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_feedback
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    int updateByExampleSelective(@Param("record") ClientFeedback record, @Param("example") ClientFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table client_feedback
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    int updateByExample(@Param("record") ClientFeedback record, @Param("example") ClientFeedbackExample example);
}