package by.pvt.dto;

import java.util.Date;

public class ClientFeedback {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_feedback.id
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_feedback.client_id
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    private Integer clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_feedback.product_id
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    private Integer productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_feedback.message
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column client_feedback.post_date
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    private Date postDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_feedback.id
     *
     * @return the value of client_feedback.id
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_feedback.id
     *
     * @param id the value for client_feedback.id
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_feedback.client_id
     *
     * @return the value of client_feedback.client_id
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    public Integer getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_feedback.client_id
     *
     * @param clientId the value for client_feedback.client_id
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    public void setClientId(Integer clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_feedback.product_id
     *
     * @return the value of client_feedback.product_id
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    public Integer getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_feedback.product_id
     *
     * @param productId the value for client_feedback.product_id
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    public void setProductId(Integer productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_feedback.message
     *
     * @return the value of client_feedback.message
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_feedback.message
     *
     * @param message the value for client_feedback.message
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column client_feedback.post_date
     *
     * @return the value of client_feedback.post_date
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    public Date getPostDate() {
        return postDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column client_feedback.post_date
     *
     * @param postDate the value for client_feedback.post_date
     *
     * @mbg.generated Fri Aug 02 16:34:35 MSK 2019
     */
    public void setPostDate(Date postDate) {
        this.postDate = postDate;
    }
}